-- Adonis CMS MySQL schema
-- Import this into the MySQL database you created in cPanel/phpMyAdmin.
-- The Node app expects these tables in MYSQL_DATABASE.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS services (
  id VARCHAR(120) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  durationMin INT NOT NULL DEFAULT 45,
  priceBDT INT NOT NULL DEFAULT 0,
  category VARCHAR(40) NOT NULL DEFAULT 'hair',
  icon VARCHAR(80) NOT NULL DEFAULT 'Scissors'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS barbers (
  id VARCHAR(120) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  experienceYears INT NOT NULL DEFAULT 0,
  specialty VARCHAR(255),
  portraitUrl TEXT,
  bio TEXT,
  rating DECIMAL(3,1) NOT NULL DEFAULT 5.0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cms_meta (
  meta_key VARCHAR(80) PRIMARY KEY,
  meta_value LONGTEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS blogs (
  id VARCHAR(120) PRIMARY KEY,
  slug VARCHAR(160) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  excerpt TEXT,
  coverImage TEXT,
  contentHtml LONGTEXT,
  seoTitle VARCHAR(255),
  seoDescription TEXT,
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bookings (
  id VARCHAR(36) PRIMARY KEY,
  clientName VARCHAR(255) NOT NULL,
  clientPhone VARCHAR(30) NOT NULL,
  clientEmail VARCHAR(255) DEFAULT '',
  branchId VARCHAR(60) NOT NULL,
  barberId VARCHAR(120) DEFAULT '',
  serviceId VARCHAR(120) DEFAULT '',
  date DATE NOT NULL,
  time VARCHAR(20) NOT NULL,
  notes TEXT,
  bookingCode VARCHAR(30) NOT NULL,
  createdAt DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO services (id, name, description, durationMin, priceBDT, category, icon) VALUES
('precision-haircut', 'Precision Haircut', 'Expert consultation, refreshing shampoo, premium haircut, sharp styling, and high-performance finish.', 45, 700, 'hair', 'Scissors'),
('skin-fade', 'Skin Fade & Modern Styling', 'Expert low/mid/high zero fade blend, hair texturizing, and high-hold pomade styling.', 60, 2500, 'hair', 'Sparkles'),
('royal-beard-shaping', 'Royal Beard Shaping', 'Beard trimming, symmetrical oil outlining, free-hand clippers sculpting, and moisturizing balm.', 30, 1200, 'beard', 'Smile'),
('hot-towel-shave', 'Hot Towel Shave', 'Classic straight razor double pass, warm pre-shave lather, facial massage with signature mint cold towel.', 40, 1500, 'beard', 'Flame'),
('hair-spa', 'Hair Spa & Treatment', 'Deep scalp detoxification, deep conditioning charcoal mask, steam activation, and shoulder stress-relief massage.', 60, 3500, 'spa', 'Flower'),
('scalp-therapy', 'Scalp Therapy', 'Soothing tea-tree cooling treatment to cure itchiness, stimulate hair follicle circulation and strengthen roots.', 45, 3000, 'spa', 'ShieldAlert'),
('facial-treatment', 'Facial Treatment', 'Adonis signature exfoliation, golden age anti-pollution face scrub, blackhead vacuum extraction, and hydrating ice therapy.', 50, 4000, 'spa', 'UserCheck'),
('vip-grooming-package', 'VIP Grooming Package', 'The ultimate royal experience: Precision Cut + Hot Towel Shave + Golden-Age Scalp Spa + Signature Facial + Specialty Beverage.', 120, 7500, 'pack', 'Crown')
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  description = VALUES(description),
  durationMin = VALUES(durationMin),
  priceBDT = VALUES(priceBDT),
  category = VALUES(category),
  icon = VALUES(icon);

INSERT INTO barbers (id, name, experienceYears, specialty, portraitUrl, bio, rating) VALUES
('tariq', 'Babul Chandra Shil', 12, 'Skin Fade & Modern Texturizing', '/assets/images/babul_barbar.png', 'Renowned stylist with 12 years of craftsmanship. Expert in razor fades and sculpting bold executive silhouettes.', 4.9),
('kamran', 'Antor Mondol', 9, 'Royal Shaves & Beard Architecture', '/assets/images/master_barber_portrait_1779269169728.png', 'A true maestro of the straight razor, specialized in symmetrical beard mapping and hot towel restoration.', 5.0),
('arif', 'Rofiqul Islam', 7, 'Classic Scissor Cuts & Scalp Health', '/assets/images/rofiq_barbar.png', 'Dedicated to traditional high-end scissor sculpting and therapeutic scalp treatments to promote long-term volume.', 4.8),
('javed', 'Chandra', 10, 'Hair Color & Keratin Treatments', '/assets/images/chandra.png', 'Color specialist with a decade of expertise in ammonia-free dye systems, keratin bonding, and high-fashion tone transformations.', 4.9),
('rohit', 'Kalu Rupa Shil', 6, 'Facial Treatments & Spa Services', '/assets/images/kalu_rupa.png', 'Certified skin-care professional with advanced training in premium facials, body scrubs, and therapeutic massage techniques.', 4.7),
('salim', 'Saimon', 8, 'Massage Therapy & Body Spa', '/assets/images/saimon.png', 'Licensed massage therapist trained in Swedish, Deep Tissue, Thai and Aroma techniques. Known for his precision pressure-point therapy.', 4.8),
('rakib', 'Dulal Chandra', 5, 'Modern Beard Styling & Waxing', '/assets/images/dulal_chandra.png', 'Young and passionate groomer specializing in contemporary beard shaping, wax-based styling, and precise razor-line finishes.', 4.6)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  experienceYears = VALUES(experienceYears),
  specialty = VALUES(specialty),
  portraitUrl = VALUES(portraitUrl),
  bio = VALUES(bio),
  rating = VALUES(rating);

INSERT INTO cms_meta (meta_key, meta_value) VALUES
('settings', JSON_OBJECT(
  'brandName', 'ADONIS',
  'brandSubtitle', 'Premium Grooming. Redefined Masculinity.',
  'heroTitle', 'Craft Your Identity With Precision',
  'heroSubtitle', 'Experience elite barbering at Adonis Men’s Grooming, where modern style meets timeless perfection in the heart of Dhaka.',
  'heroBg', '/assets/images/adonis_executive_lounge_1779270704894.png',
  'aboutStory', 'Adonis Men’s Grooming is a premium barbershop brand in Dhaka dedicated to redefining modern masculinity through precision grooming, luxury service, and personalized styling. Every cut, shave, and treatment is designed to elevate confidence and identity.',
  'aboutDescription', 'We believe that grooming is not merely a transaction—it represents a curated ritual of premium transition. Nestled in Dhaka’s premier neighborhoods, Adonis pairs classic European barber heritage with high-end, contemporary Dubai hotel-standard lounge accommodations. From the selection of our premium organic grooming balms to the exact temperature parameters of our steaming mint towels, every detail is meticulously orchestrated to deliver perfection.',
  'contactEmail', 'info@adonis.com.bd',
  'openHoursDays', 'Everyday (Sat - Fri)',
  'openHoursTime', '10:00 AM – 10:00 PM',
  'phoneNumbers', JSON_ARRAY('+880 1919-700800', '+880 1700-600333'),
  'facebookUrl', 'https://facebook.com/adonis.bd',
  'instagramUrl', 'https://instagram.com/adonis.grooming',
  'whatsappUrl', 'https://wa.me/8801919700800'
)),
('smtp', JSON_OBJECT(
  'host', '',
  'port', 587,
  'secure', false,
  'user', '',
  'pass', '',
  'fromEmail', 'noreply@adonis.com.bd',
  'adminEmails', 'admin@adonis.com.bd'
))
ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);

INSERT INTO blogs (id, slug, title, excerpt, coverImage, contentHtml, seoTitle, seoDescription, status, createdAt, updatedAt) VALUES
(
  'premium-mens-grooming-dhaka',
  'premium-mens-grooming-dhaka',
  'Premium Men’s Grooming in Dhaka: The Adonis Guide to a Sharper Look',
  'Discover how professional haircuts, beard shaping, facials, massage, and premium salon care help modern men in Dhaka look sharper and feel more confident.',
  '/assets/images/adonis_styling_chairs_1779270725139.png',
  '<h2>Why Men’s Grooming Matters More Than Ever</h2><p>Modern grooming is not only about looking polished. It is about confidence, hygiene, presentation, and personal identity. At <strong>Adonis Men’s Grooming in Dhaka</strong>, every service is designed to help men look sharp while enjoying a calm, premium salon experience.</p><h3>Precision Haircuts for Every Lifestyle</h3><p>A professional haircut should match your face shape, profession, hair texture, and daily styling routine. Whether you prefer a classic scissor cut, a modern skin fade, or a refined executive style, the right haircut can instantly improve your overall appearance.</p><ul><li>Clean fades and sharp blending</li><li>Face-shape-based consultation</li><li>Professional styling and finishing</li></ul><h3>Beard Shaping and Hot Towel Shaves</h3><p>For men with facial hair, beard maintenance is essential. A balanced beard line, clean cheek contour, and sharp neckline can define the jaw and create a more structured look. Hot towel shaving also refreshes the skin and delivers a traditional barbering experience.</p><h4>Facials, Spa Care, and Relaxation</h4><p>Dhaka’s weather, dust, and stress can affect skin and scalp health. Premium facials, hair spa treatments, massage, and body care help restore freshness and reduce everyday fatigue.</p><h5>Why Choose Adonis?</h5><p><strong>Adonis Men’s Grooming</strong> combines expert stylists, premium products, luxury interiors, and personalized service for men who expect more than a basic haircut.</p><h6>Book Your Premium Grooming Session</h6><p>If you are searching for a premium men’s salon in Dhaka, visit Adonis in Gulshan or Bashundhara and experience grooming designed around confidence, comfort, and detail.</p>',
  'Premium Men’s Grooming in Dhaka | Adonis Men’s Grooming',
  'Looking for the best men’s grooming salon in Dhaka? Learn how Adonis combines precision haircuts, beard styling, facials, spa care, and premium salon service.',
  'published',
  '2026-06-04 00:00:00',
  '2026-06-04 00:00:00'
)
ON DUPLICATE KEY UPDATE
  slug = VALUES(slug),
  title = VALUES(title),
  excerpt = VALUES(excerpt),
  coverImage = VALUES(coverImage),
  contentHtml = VALUES(contentHtml),
  seoTitle = VALUES(seoTitle),
  seoDescription = VALUES(seoDescription),
  status = VALUES(status),
  updatedAt = VALUES(updatedAt);



CREATE TABLE IF NOT EXISTS price_list_items (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  category varchar(100) NOT NULL,
  name varchar(255) NOT NULL,
  price varchar(60) NOT NULL,
  description text DEFAULT NULL,
  branch_id varchar(60) DEFAULT 'all',
  sort_order int(11) NOT NULL DEFAULT 0,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO price_list_items (id, category, name, price, description, branch_id, sort_order) VALUES
(1, 'HAIR CUTTING', 'Hair Cut with Shampoo', '700/-', 'Classic precise cut with professional wash styling finish', 'gulshan', 0),
(2, 'HAIR CUTTING', 'Hair Cut Stylish / Fashion / Catalogue', '1,000/- & Above', 'Trending, aesthetic styles suited for elite bone-structures', 'gulshan', 1),
(3, 'HAIR CUTTING', 'Normal Beard Trim', '600/-', 'Symmetrical trim with razor lines finish', 'gulshan', 2),
(4, 'HAIR CUTTING', 'Stylish Beard Trim', '600/- & Above', 'Beard mapping, precise styling and defining', 'gulshan', 3),
(5, 'HAIR CUTTING', 'Shave', '600/-', 'Smooth face, premium shaving foam and moisturization', 'gulshan', 4),
(6, 'HAIR CUTTING', 'Bald Adult', '700/-', 'Clean skull head shave with soothing balm treatment', 'gulshan', 5),
(7, 'HAIR CUTTING', 'Bald Infant / Children', '700/-', 'Careful children or infant skull shave with extra sensitivity care', 'gulshan', 6),
(8, 'HAIR SETTING', 'Hair Setting Mousse / Cream / Gel / Spray / Wax', '500/-', 'Professional holding finish', 'gulshan', 0),
(9, 'HAIR SETTING', 'Hair Shampoo with Conditioner', '500/-', 'Deep cleanse with premium hydration', 'gulshan', 1),
(10, 'HAIR SETTING', 'Blow Dry', '500/-', 'Volume building blow action styling', 'gulshan', 2),
(11, 'HAIR SETTING', 'Hair Iron', '2,000/- & Above', 'Flat iron straight styling texture', 'gulshan', 3),
(12, 'HAIR SETTING', 'Hair Rebonding', '10,000/- & Above', 'Permanent elite hair straight restructuring', 'gulshan', 4),
(13, 'HAIR SETTING', 'Super Shine Keratin', '16,000/- & Above', 'Ultimate premium silk infusion keratin shield', 'gulshan', 5),
(14, 'SPECIAL CHARGE LIST', 'Shower & Steam', '1,000/-', 'Relieving warm shower and professional steam session', 'gulshan', 0),
(15, 'SPECIAL CHARGE LIST', 'Personal Room Charge', '1,000/-', 'Private suite reservation with completely exclusive styling', 'gulshan', 1),
(16, 'SPECIAL CHARGE LIST', 'Sauna', '1,000/-', 'Elite dry heat detoxification chamber access', 'gulshan', 2),
(17, 'SPECIAL CHARGE LIST', 'Home Service', '2,000/-', 'Premium door-to-door styling with master barber sent to your residence', 'gulshan', 3),
(18, 'HAIR DYE & OTHERS', 'Moustache Dye', '600/-', 'Quick moustache grey coverage', 'gulshan', 0),
(19, 'HAIR DYE & OTHERS', 'Beard Dye Ammonia Free Bigen', '1,000/-', 'Safe ammonia-free beard contour dye', 'gulshan', 1),
(20, 'HAIR DYE & OTHERS', 'Beard Dye with Inova Color', '1,500/-', 'Rich deep color tone alignment', 'gulshan', 2),
(21, 'HAIR DYE & OTHERS', 'Dye Color Apply Only Service Charge + Shampoo', '1,000/- & Above', 'Using client\'s custom self-purchased dye', 'gulshan', 3),
(22, 'HAIR DYE & OTHERS', 'Color Apply Charge', '1,000/- & Above', 'Professional expert dye application service', 'gulshan', 4),
(23, 'HAIR DYE & OTHERS', 'Color Sticks Each Color', '1,000/- & Above', 'Bespoke design highlight streaks', 'gulshan', 5),
(24, 'HAIR DYE & OTHERS', 'Bigen', '1,300/-', 'Traditional coverage formula', 'gulshan', 6),
(25, 'HAIR DYE & OTHERS', 'Bigen Ammonia Free', '1,800/-', 'Non-irritant natural formula', 'gulshan', 7),
(26, 'HAIR DYE & OTHERS', 'Mehedi Color', '2,000/- & Above', 'Traditional organic natural henna styling', 'gulshan', 8),
(27, 'HAIR DYE & OTHERS', 'L\'Oréal Majirel Color', '2,500/-', 'Premium premium dye with radiant shine', 'gulshan', 9),
(28, 'HAIR DYE & OTHERS', 'L\'Oréal INOA Ammonia Free', '3,000/-', 'Elite zero ammonia protective hair color', 'gulshan', 10),
(29, 'HAIR DYE & OTHERS', 'Keune Color Ammonia Free', '3,000/- & Above', 'Top professional hair care coloring', 'gulshan', 11),
(30, 'HAIR DYE & OTHERS', 'Fashion Color with Pre-lightening', '9,000/- & Above', 'Extreme ash, grey or blonde high-fashion tone transformations', 'gulshan', 12),
(31, 'HAIR DYE & OTHERS', 'Godrej Professional Hair Color', '3,500/- & Above', 'Professional color system', 'gulshan', 13),
(32, 'HAIR TREATMENT', 'Hot Oil Massage with Steam Coconut Oil', '1,000/- & Above', 'Relieving warm oil therapy with intense steam', 'gulshan', 0),
(33, 'HAIR TREATMENT', 'Hot Oil Massage with Steam Castor / Almond / Shahanaj / Garlic Oil', '1,500/-', 'Specific selected essential oils for target remedies', 'gulshan', 1),
(34, 'HAIR TREATMENT', 'Hot Oil Massage with Steam Godrej Argan or Acai Oil', '1,500/-', 'Ultra premium hydration oils', 'gulshan', 2),
(35, 'HAIR TREATMENT', 'Hot Oil Massage with Steam Body Shop Coco Oil', '1,800/-', 'Imported Body Shop Coco formula treatment', 'gulshan', 3),
(36, 'HAIR TREATMENT', 'Hot Oil Therapy with Aloe Vera Pack', '2,000/- & Above', 'Anti-allergy organic hair cooling pack', 'gulshan', 4),
(37, 'HAIR TREATMENT', 'L\'Oréal Hair Spa', '2,800/-', 'Deep L\'Oréal hair nourishment treatment', 'gulshan', 5),
(38, 'HAIR TREATMENT', 'Godrej Hair Spa', '3,000/-', 'Professional hair mask with steam', 'gulshan', 6),
(39, 'HAIR TREATMENT', 'Hair Shine', '3,000/-', 'Intense glass reflecting hair gloss finish', 'gulshan', 7),
(40, 'HAIR TREATMENT', 'Treatment for Rebonding Hair', '3,500/-', 'Reconstructive conditioning for chemically straightened hair', 'gulshan', 8),
(41, 'HAIR TREATMENT', 'Godrej Hair Treatment Dry & Damaged Hair', '4,000/-', 'Target repair for splitting or over-processed hair', 'gulshan', 9),
(42, 'HAIR TREATMENT', 'Godrej Hair Treatment Regular & Dry Hair', '4,000/-', 'Normalizing hydration booster', 'gulshan', 10),
(43, 'HAIR TREATMENT', 'Godrej Hair Treatment Frizzy & Straightened Hair', '4,000/-', 'Sleek smoothing therapy for high-frizz cases', 'gulshan', 11),
(44, 'HAIR TREATMENT', 'L\'Oréal Elvive Dandruff Control / Hair Fall / Damage', '4,500/-', 'Intensive scalp relief remedies', 'gulshan', 12),
(45, 'HAIR TREATMENT', 'Godrej Kera Care Keratin Treatment', '5,000/-', 'Premium keratin structure builder', 'gulshan', 13),
(46, 'HAIR TREATMENT', 'Garnier Treatment', '5,000/-', 'Natural extract conditioning', 'gulshan', 14),
(47, 'HAIR TREATMENT', 'Body Shop Hair Treatment', '7,000/-', 'Ultra-luxurious premium imported therapy', 'gulshan', 15),
(48, 'HAIR TREATMENT', 'Ginger Hair Treatment', '8,000/-', 'Ultimate deep-cleansing organic anti-dandruff ginger therapy', 'gulshan', 16),
(49, 'FACE MASSAGE & SCRUB', 'Face Massage', '1,500/-', 'Relieving traditional facial muscles relaxation', 'gulshan', 0),
(50, 'FACE MASSAGE & SCRUB', 'Body Shop Face Massage Vitamin C', '3,000/-', 'Glow-boosting skin brightening workout', 'gulshan', 1),
(51, 'FACE MASSAGE & SCRUB', 'Special Face Massage Body Shop Vitamin E', '4,000/-', 'Anti-aging cells repair & deep moisture nutrition', 'gulshan', 2),
(52, 'FAIR POLISH', 'Face Polish', '1,200/-', 'Exfoliating glow application', 'gulshan', 0),
(53, 'FAIR POLISH', 'Neck Polish', '800/-', 'Clean color adjustment', 'gulshan', 1),
(54, 'FAIR POLISH', 'Face + Neck Polish', '1,800/-', 'Complete head-neck brightness polish', 'gulshan', 2),
(55, 'FAIR POLISH', 'Hands Polish', '2,000/-', 'Dual arm exfoliation and tone matching', 'gulshan', 3),
(56, 'FAIR POLISH', 'Half Body Front Polish', '2,500/-', 'Torso skin restoration', 'gulshan', 4),
(57, 'FAIR POLISH', 'Half Body Back Polish', '3,000/-', 'Spine skin polish with steam', 'gulshan', 5),
(58, 'FAIR POLISH', 'Face + Neck + Hands Polish', '3,000/-', 'Highly popular complete visual grooming combo', 'gulshan', 6),
(59, 'FAIR POLISH', 'Upper Body Polish', '4,500/-', 'Complete waist-up whitening polish', 'gulshan', 7),
(60, 'FAIR POLISH', 'Full Body Polish', '6,000/-', 'The absolute full body skin renewal experience', 'gulshan', 8),
(61, 'MILK FAIR POLISH', 'Face + Neck (Milk)', '3,000/-', 'Lactic acid whitening and hydration for face and neck', 'gulshan', 0),
(62, 'MILK FAIR POLISH', 'Front & Back (Milk)', '12,000/-', 'Torso-wide deluxe milk polish', 'gulshan', 1),
(63, 'MILK FAIR POLISH', 'Full Body (Milk)', '15,000/-', 'Ultimate royal skin hydration and tone leveling', 'gulshan', 2),
(64, 'FACIAL', 'Adonis Special Facial', '3,500/-', 'Our signature charcoal blend for active city lifestyles', 'gulshan', 0),
(65, 'FACIAL', 'Aloe Vera Facial', '3,500/-', 'Soothing hydration for highly sensitive or sun-irritated skins', 'gulshan', 1),
(66, 'FACIAL', 'Pearl Facial', '4,500/-', 'Deluxe mineral-based face glow facial', 'gulshan', 2),
(67, 'FACIAL', 'Diamond Facial', '5,000/-', 'Deep micro-exfoliation and light reflecting brightness limit', 'gulshan', 3),
(68, 'FACIAL', 'Gold Facial', '6,000/-', 'Premium 24k gold leaf skin recovery and glow action', 'gulshan', 4),
(69, 'FACIAL', 'Janssen Whitening Facial', '8,000/-', 'Aesthetic-level German Janssen formula', 'gulshan', 5),
(70, 'FACIAL', 'Lotus Gold Facial', '8,000/-', 'Ultra premium luxury natural extracts gold treatment', 'gulshan', 6),
(71, 'FACIAL', 'Body Shop Vitamin C Facial', '8,000/-', 'Rich vitamin C active glow remedy', 'gulshan', 7),
(72, 'FACIAL', 'Janssen Whitening Facial Orange', '9,000/-', 'Premium citric Janssen formula', 'gulshan', 8),
(73, 'FACIAL', 'S K 5 Diamond Facial', '10,000/-', 'Super premium cell replacement and luxury glow', 'gulshan', 9),
(74, 'FACIAL', 'Body Shop Seaweed Facial', '10,000/-', 'Intense minerals oil control marine treatment', 'gulshan', 10),
(75, 'FACIAL', 'Body Shop Drops of Light Facial', '12,000/-', 'The ultimate luxury imported brightening program', 'gulshan', 11),
(76, 'BODY FASHION & WAX', 'Eye Brows Shaping', '500/-', 'Elite thread layout shaping', 'gulshan', 0),
(77, 'BODY FASHION & WAX', 'Face Threading', '1,000/- & Above', 'Clean smooth facial threading', 'gulshan', 1),
(78, 'BODY FASHION & WAX', 'Ears Candling', '2,500/-', 'Traditional thermal wax ear canal detox and pressure relief', 'gulshan', 2),
(79, 'BODY FASHION & WAX', 'Waxing Face', '1,000/-', 'Smooth face waxing', 'gulshan', 3),
(80, 'BODY FASHION & WAX', 'Waxing Neck', '1,000/-', 'Hygienic neck skin wax', 'gulshan', 4),
(81, 'BODY FASHION & WAX', 'Waxing Nose / Ear', '1,000/-', 'Pain-free premium interior wax', 'gulshan', 5),
(82, 'BODY FASHION & WAX', 'Waxing Hands', '2,000/-', 'Full arm waxing', 'gulshan', 6),
(83, 'BODY FASHION & WAX', 'Waxing Back Upper Body', '3,000/-', 'Upper back wax', 'gulshan', 7),
(84, 'BODY FASHION & WAX', 'Waxing Half Legs / Full Legs', '3,000/- & Above', 'Leg area hair removal', 'gulshan', 8),
(85, 'BODY FASHION & WAX', 'Waxing Front Upper Body', '3,500/-', 'Chest and stomach area wax', 'gulshan', 9),
(86, 'BODY FASHION & WAX', 'Waxing Half Body (Neck+Hands+Front+Back)', '6,000/- & Above', 'Comprehensive upper torso wax package', 'gulshan', 10),
(87, 'BODY FASHION & WAX', 'Waxing Full Body', '10,000/-', 'Complete full body premium hair removal wax', 'gulshan', 11),
(88, 'SPA & BODY SCRUB', 'Aromatic Bath (15 Minutes)', '10,000/-', 'Relaxing jacuzzi-level warm bath infused with premium essential oils', 'gulshan', 0),
(89, 'SPA & BODY SCRUB', 'Full Body Scrub with Steam', '5,500/- & Above', 'Organic dermabrasion scrub followed by complete hot steam', 'gulshan', 1),
(90, 'SPA & BODY SCRUB', 'Back Scrub', '2,400/- & Above', 'Shedding dead cells, deep cleansing', 'gulshan', 2),
(91, 'SPA & BODY SCRUB', 'Leg Scrub', '1,200/-', 'Exfoliation for legs', 'gulshan', 3),
(92, 'SPA & BODY SCRUB', 'Hand Scrub', '1,000/-', 'Smooth, hydrating hand scrub', 'gulshan', 4),
(93, 'SPA & BODY SCRUB', 'Body Shop Full Body Scrub with Steam', '11,000/-', 'Super premium imported Body Shop exfoliation', 'gulshan', 5),
(94, 'SPA & BODY SCRUB', 'Body Smoothing Scrub', '8,000/-', 'Cell renewal visual smoothing scrub', 'gulshan', 6),
(95, 'SPA & BODY SCRUB', 'Unilever Scrub Full Body Scrub', '6,500/-', 'Clean, hydrating scrub combo', 'gulshan', 7),
(96, 'SPA & BODY SCRUB', 'Body Shop Hand Scrub', '2,000/-', 'Premium hydration and shine', 'gulshan', 8),
(97, 'SPA & BODY SCRUB', 'Body Shop Back Scrub', '6,000/-', 'Advanced spine smoothing and steam', 'gulshan', 9),
(98, 'SPA & BODY SCRUB', 'Body Shop Foot Scrub', '2,000/-', 'Dead skin removal with deep moisturizing', 'gulshan', 10),
(99, 'SPA & BODY SCRUB', 'Aloe Vera Body Scrub Full Body', '5,000/-', 'Sensitive skin safe cooling full body scrub', 'gulshan', 11),
(100, 'SPA & BODY SCRUB', 'Royal Body Smoothing Scrub', '16,000/-', 'The absolute pinnacle of luxury full body pampering', 'gulshan', 12),
(101, 'HAND & FOOT CARE', 'Manicure', '800/-', 'Clean cuticle trim, buffing, and hand cream', 'gulshan', 0),
(102, 'HAND & FOOT CARE', 'Pedicure', '1,200/-', 'Deep foot soak, heel scrubbing, and massage', 'gulshan', 1),
(103, 'HAND & FOOT CARE', 'Manicure Deluxe', '1,200/-', 'Warm oils massage, paraffin mask hydration', 'gulshan', 2),
(104, 'HAND & FOOT CARE', 'Pedicure Deluxe', '2,300/-', 'Signature premium mud mask, hot stone massage', 'gulshan', 3),
(105, 'MASSAGE LAB', 'Neck, Head & Foot Massage (60 Mins)', '2,200/-', 'Full tension release combo', 'gulshan', 0),
(106, 'MASSAGE LAB', 'Neck, Head & Foot Massage (90 Mins)', '3,000/-', 'Extended relieving treatment', 'gulshan', 1),
(107, 'MASSAGE LAB', 'Back, Neck & Shoulder Massage (30 Mins)', '1,500/-', 'Quick trigger points de-stress', 'gulshan', 2),
(108, 'MASSAGE LAB', 'Thai Foot Reflexology (45 Mins)', '1,200/-', 'Pressure points mapping for overall body energy', 'gulshan', 3),
(109, 'MASSAGE LAB', 'Thai Foot Reflexology (60 Mins)', '1,600/-', 'Standard reflex massage', 'gulshan', 4),
(110, 'MASSAGE LAB', 'Thai Foot Reflexology (90 Mins)', '2,200/-', 'Ultimate leg and nervous recovery', 'gulshan', 5),
(111, 'MASSAGE LAB', 'Head Massage with Hair Tonic (15 Mins)', '1,000/-', 'Deep cerebral massage with nutrient-rich liquid', 'gulshan', 6),
(112, 'MASSAGE LAB', 'Head Massage without Hair Tonic (15 Mins)', '600/-', 'Standard dry scalp soothing massage', 'gulshan', 7),
(113, 'MASSAGE LAB', 'Chair Massage (20 Mins)', '1,200/-', 'Ergonomic neck-to-hip quick massage', 'gulshan', 8),
(114, 'MASSAGE LAB', 'Bamboo Massage (60 Mins)', '3,500/-', 'Warm bamboo rods rolling to break deep muscle fibers', 'gulshan', 9),
(115, 'MASSAGE LAB', 'Bamboo Massage (90 Mins)', '4,800/-', 'Extended deep tension bamboo therapy', 'gulshan', 10),
(116, 'MASSAGE LAB', 'Hot Stone Massage (60 Mins)', '3,800/-', 'Therapeutic warm volcanic basalt stones layout', 'gulshan', 11),
(117, 'MASSAGE LAB', 'Hot Stone Massage (90 Mins)', '5,000/-', 'Deep heat thermal stone recovery', 'gulshan', 12),
(118, 'MASSAGE LAB', 'Swedish Massage (60 Mins)', '3,200/-', 'Classic long-stroke circulatory massage', 'gulshan', 13),
(119, 'MASSAGE LAB', 'Swedish Massage (90 Mins)', '4,200/-', 'Ultimate light-to-medium relax', 'gulshan', 14),
(120, 'MASSAGE LAB', 'Aroma Massage (60 Mins)', '2,800/-', 'Lavendar/Eucalyptus therapeutic essential oil massage', 'gulshan', 15),
(121, 'MASSAGE LAB', 'Aroma Massage (90 Mins)', '3,700/-', 'Total aromatherapy recharge', 'gulshan', 16),
(122, 'MASSAGE LAB', 'Indian / Traditional Massage (60 Mins)', '2,500/-', 'Deep kneading physical muscle reset', 'gulshan', 17),
(123, 'MASSAGE LAB', 'Indian / Traditional Massage (90 Mins)', '3,500/-', 'Full body restorative massage', 'gulshan', 18),
(124, 'MASSAGE LAB', 'Deep Tissue Body Massage (60 Mins)', '3,200/-', 'High-pressure physical knot removal', 'gulshan', 19),
(125, 'MASSAGE LAB', 'Deep Tissue Body Massage (90 Mins)', '4,200/-', 'Maestra muscle restoration', 'gulshan', 20),
(126, 'MASSAGE LAB', 'Thai Body Massage (60 Mins)', '3,200/-', 'Passive yoga stretches, compressions', 'gulshan', 21),
(127, 'MASSAGE LAB', 'Thai Body Massage (90 Mins)', '4,200/-', 'Extended physical stretch alignment', 'gulshan', 22),
(128, 'SPORTS & CUPPING', 'Back Cupping with 30 Min Massage', '4,000/-', 'Detoxifying vacuum cupping of the back', 'gulshan', 0),
(129, 'SPORTS & CUPPING', 'Full Body Cupping with 30 Min Massage', '7,000/-', 'Full-body muscle blood flow cupping activation', 'gulshan', 1),
(130, 'SPORTS & CUPPING', 'Sports Massage (90 Mins)', '5,500/-', 'High-intensity athletic relief and joint flexibility', 'gulshan', 2),
(131, 'SPORTS & CUPPING', 'Back Fire Cupping with 30 Min Massage', '7,000/-', 'Traditional dynamic heat vacuum cupping therapy', 'gulshan', 3),
(132, 'SPORTS & CUPPING', 'Full Body Fire Cupping with 30 Min Massage', '10,000/-', 'The peak physical recovery standard for high fatigue', 'gulshan', 4),
(133, 'MAKE-OVER ART', 'Groom Make-Up', '4,000/-', 'Blemish-free high definition camera matching groom facial setting', 'gulshan', 0),
(134, 'MAKE-OVER ART', 'Studio / Model Make-Up', '6,000/-', 'Studio flash-safe professional modeling look design', 'gulshan', 1),
(135, 'HAIR CUTTING', 'Hair Cut with Shampoo', '700/-', NULL, 'bashundhara', 0),
(136, 'HAIR CUTTING', 'Hair Cut (Stylish/Fashion/Catalogue)', '1,000/- & Above', NULL, 'bashundhara', 1),
(137, 'HAIR CUTTING', 'Normal Beard Trim', '500/-', NULL, 'bashundhara', 2),
(138, 'HAIR CUTTING', 'Stylish Beard Trim', '600/- & Above', NULL, 'bashundhara', 3),
(139, 'HAIR CUTTING', 'Shave', '500/-', NULL, 'bashundhara', 4),
(140, 'HAIR CUTTING', 'Bald-Adult', '700/-', NULL, 'bashundhara', 5),
(141, 'HAIR CUTTING', 'Bald-Infant/Children', '700/-', NULL, 'bashundhara', 6),
(142, 'HAIR SETTING', 'Hair Setting (Mousse/Cream/Gel/Spray/Wax)', '500/-', NULL, 'bashundhara', 0),
(143, 'HAIR SETTING', 'Hair Shampoo With Conditioner', '500/-', NULL, 'bashundhara', 1),
(144, 'HAIR SETTING', 'Blow Dry', '500/-', NULL, 'bashundhara', 2),
(145, 'HAIR SETTING', 'Hair Iron', '2,000/- & Above', NULL, 'bashundhara', 3),
(146, 'HAIR SETTING', 'Hair Rebonding', '10,000/- & Above', NULL, 'bashundhara', 4),
(147, 'HAIR SETTING', 'Super Shine Karateen', '16,000/- & Above', NULL, 'bashundhara', 5),
(148, 'SPECIAL CHARGE LIST', 'Shower & Steam (30 Min)', '1,000/-', NULL, 'bashundhara', 0),
(149, 'SPECIAL CHARGE LIST', 'Shower without Steam', '500/-', NULL, 'bashundhara', 1),
(150, 'SPECIAL CHARGE LIST', 'Personal Room Charge', '1,000/-', NULL, 'bashundhara', 2),
(151, 'SPECIAL CHARGE LIST', 'Sauna', '1,000/-', NULL, 'bashundhara', 3),
(152, 'SPECIAL CHARGE LIST', 'Home Service', '2,000/-', NULL, 'bashundhara', 4),
(153, 'HAIR TREATMENT', 'Hot Oil Massage with steam (Harbal Oil)', '1,000/- & Above', NULL, 'bashundhara', 0),
(154, 'HAIR TREATMENT', 'Hot Oil Massage with steam (Castor Oil)', '1,000/-', NULL, 'bashundhara', 1),
(155, 'HAIR TREATMENT', 'Hot Oil Massage with steam (Almond Oil)', '1,200/-', NULL, 'bashundhara', 2),
(156, 'HAIR TREATMENT', 'Hot Oil Massage with steam (Argan Shahanaj Oil)', '1,500/-', NULL, 'bashundhara', 3),
(157, 'HAIR TREATMENT', 'Hot Oil Massage with steam (Garlic Oil)', '1,500/-', NULL, 'bashundhara', 4),
(158, 'HAIR TREATMENT', 'Hot Oil Massage with steam (Body Shop Coco Oil)', '1,800/-', NULL, 'bashundhara', 5),
(159, 'HAIR TREATMENT', 'Hot Oil Therapy with Alovera Pack', '2,000/- & Above', NULL, 'bashundhara', 6),
(160, 'HAIR TREATMENT', 'Caring Hair SPA', '2,000/-', NULL, 'bashundhara', 7),
(161, 'HAIR TREATMENT', 'L’OREAL Hair SPA', '2,200/-', NULL, 'bashundhara', 8),
(162, 'HAIR TREATMENT', 'Hair Shine (Temporary shine enhancement before any special events or party)', '3,000/-', NULL, 'bashundhara', 9),
(163, 'HAIR TREATMENT', 'Treatment for Rebonding Hair', '3,000/-', NULL, 'bashundhara', 10),
(164, 'HAIR TREATMENT', 'Zem Treatment', '3,000/-', NULL, 'bashundhara', 11),
(165, 'HAIR TREATMENT', 'Keratin Treatment', '3,200/-', NULL, 'bashundhara', 12),
(166, 'HAIR TREATMENT', 'L’OREAL (Treatment for hair Loss, dry & Sensetive scalp)', '4,000/-', NULL, 'bashundhara', 13),
(167, 'HAIR TREATMENT', 'L’OREAL (Treatment for dandruff Control)', '4,000/-', NULL, 'bashundhara', 14),
(168, 'HAIR TREATMENT', 'European Treatment (Dandruff)', '4,000/-', NULL, 'bashundhara', 15),
(169, 'HAIR TREATMENT', 'European Treatment (Hair Fall)', '4,000/-', NULL, 'bashundhara', 16),
(170, 'HAIR TREATMENT', 'European Treatment (Damage)', '4,000/-', NULL, 'bashundhara', 17),
(171, 'HAIR TREATMENT', 'Organ Treatment', '4,500/-', NULL, 'bashundhara', 18),
(172, 'HAIR TREATMENT', 'Garnear Treatment', '5,000/-', NULL, 'bashundhara', 19),
(173, 'HAIR TREATMENT', 'VLCC Hair Treatment Dandruff', '6,000/-', NULL, 'bashundhara', 20),
(174, 'HAIR TREATMENT', 'VLCC Hair Treatment Hair Fall', '6,000/-', NULL, 'bashundhara', 21),
(175, 'HAIR TREATMENT', 'Body Shop Hair Treatment', '7,000/-', NULL, 'bashundhara', 22),
(176, 'HAIR TREATMENT', 'Ginger Hair Treatment', '8,000/-', NULL, 'bashundhara', 23),
(177, 'HAIR TREATMENT', 'Olafex Hair Treatment', '9,000/-', NULL, 'bashundhara', 24),
(178, 'FACE MASSAGE & SCRUB', 'Stacy Face Massage', '1,500/-', NULL, 'bashundhara', 0),
(179, 'FACE MASSAGE & SCRUB', 'Body Shop Face Massage Vitamin-C', '2,500/-', NULL, 'bashundhara', 1),
(180, 'FACE MASSAGE & SCRUB', 'Special Face Massage (Body Shop) Vitamin-E', '3,500/-', NULL, 'bashundhara', 2),
(181, 'FAIR POLISH', 'Face', '1,000/-', NULL, 'bashundhara', 0),
(182, 'FAIR POLISH', 'Neck', '600/-', NULL, 'bashundhara', 1),
(183, 'FAIR POLISH', 'Face + Neck', '1,500/-', NULL, 'bashundhara', 2),
(184, 'FAIR POLISH', 'Hands', '1,500/-', NULL, 'bashundhara', 3),
(185, 'FAIR POLISH', 'Half body - Front', '2,000/-', NULL, 'bashundhara', 4),
(186, 'FAIR POLISH', 'Half body - back', '2,500/-', NULL, 'bashundhara', 5),
(187, 'FAIR POLISH', 'Face + Neck + Hands', '2,500/-', NULL, 'bashundhara', 6),
(188, 'FAIR POLISH', 'Upper Body', '4,000/-', NULL, 'bashundhara', 7),
(189, 'FAIR POLISH', 'Full body', '5,000/-', NULL, 'bashundhara', 8),
(190, 'MILK FAIR POLISH', 'Face + Neck', '3,000/-', NULL, 'bashundhara', 0),
(191, 'MILK FAIR POLISH', 'Front & Back', '12,000/-', NULL, 'bashundhara', 1),
(192, 'MILK FAIR POLISH', 'Full Body', '15,000/-', NULL, 'bashundhara', 2),
(193, 'HAIR DYE & OTHERS', 'Moustache Dye', '500/-', NULL, 'bashundhara', 0),
(194, 'HAIR DYE & OTHERS', 'Beard Dye (Ammonia Free) Bigen', '1,000/-', NULL, 'bashundhara', 1),
(195, 'HAIR DYE & OTHERS', 'Beard Dye with Inova Color', '1,500/-', NULL, 'bashundhara', 2),
(196, 'HAIR DYE & OTHERS', 'Dye Color apply only (Service charge)+Shampoo', '800/- & above', NULL, 'bashundhara', 3),
(197, 'HAIR DYE & OTHERS', 'Color Apply Charge', '1,000/- & above', NULL, 'bashundhara', 4),
(198, 'HAIR DYE & OTHERS', 'Hi-Speed', '1,500/-', NULL, 'bashundhara', 5),
(199, 'HAIR DYE & OTHERS', 'Bigen', '1,200/-', NULL, 'bashundhara', 6),
(200, 'HAIR DYE & OTHERS', 'Bigen (Ammonia Free)', '1,600/-', NULL, 'bashundhara', 7),
(201, 'HAIR DYE & OTHERS', 'Mehedi Color', '2,000/- & above', NULL, 'bashundhara', 8),
(202, 'HAIR DYE & OTHERS', 'Just for Man Color', '2,500/-', NULL, 'bashundhara', 9),
(203, 'HAIR DYE & OTHERS', 'L’Oréal Majnel Color', '2,500/-', NULL, 'bashundhara', 10),
(204, 'HAIR DYE & OTHERS', 'L’Oréal INOA (Ammonia Free)', '3,000/-', NULL, 'bashundhara', 11),
(205, 'HAIR DYE & OTHERS', 'Keune Color (Ammonia Free)', '3,000/- & above', NULL, 'bashundhara', 12),
(206, 'HAIR DYE & OTHERS', 'Color sticks (Each colors)', '1,000/- & above', NULL, 'bashundhara', 13),
(207, 'HAIR DYE & OTHERS', 'Fashion Color with Pre-lightening', '9,000/- & above', NULL, 'bashundhara', 14),
(208, 'BODY FASHION & WAX', 'Eye Brows', '300/-', NULL, 'bashundhara', 0),
(209, 'BODY FASHION & WAX', 'Face Threading', '600/- & Above', NULL, 'bashundhara', 1),
(210, 'BODY FASHION & WAX', 'Ears Candeling', '4,000/-', NULL, 'bashundhara', 2),
(211, 'BODY FASHION & WAX', 'Waxing-Face', '1,000/-', NULL, 'bashundhara', 3),
(212, 'BODY FASHION & WAX', 'Waxing-Neck', '600/-', NULL, 'bashundhara', 4),
(213, 'BODY FASHION & WAX', 'Waxing-Hands', '2,000/-', NULL, 'bashundhara', 5),
(214, 'BODY FASHION & WAX', 'Waxing-Back-Upper body', '3,000/-', NULL, 'bashundhara', 6),
(215, 'BODY FASHION & WAX', 'Waxing-Front-Upper body', '3,000/-', NULL, 'bashundhara', 7),
(216, 'BODY FASHION & WAX', 'Waxing-(Half Legs-Full Legs)', '2,000/- & Above', NULL, 'bashundhara', 8),
(217, 'BODY FASHION & WAX', 'Waxing-Half Body (Neck+Hands+Front & Back)', '6,000/- & Above', NULL, 'bashundhara', 9),
(218, 'BODY FASHION & WAX', 'Waxing-Full Body', '8,000/-', NULL, 'bashundhara', 10),
(219, 'BODY FASHION & WAX', 'Waxing-Nose, Ear', '1,000/-', NULL, 'bashundhara', 11),
(220, 'SPA & BODY SCRUB', 'Body Spa', '9,000/-', 'Basic Pedicure & Manicure (45 Minutes), Aroma Relaxing massage (45 Minutes), Herbal Body pack (25 Minutes), Aromatic Bath (15 Minutes)', 'bashundhara', 0),
(221, 'SPA & BODY SCRUB', 'Full body scrub with steam', '4,000/- & Above', NULL, 'bashundhara', 1),
(222, 'SPA & BODY SCRUB', 'Back scrub', '2,000/- & Above', NULL, 'bashundhara', 2),
(223, 'SPA & BODY SCRUB', 'Leg Scrub', '1,200/-', NULL, 'bashundhara', 3),
(224, 'SPA & BODY SCRUB', 'Hand scrub', '1,000/-', NULL, 'bashundhara', 4),
(225, 'SPA & BODY SCRUB', 'Body Shop Full Body scrub with steam', '10,000/-', NULL, 'bashundhara', 5),
(226, 'SPA & BODY SCRUB', 'Body Smoothing Scrab', '8,000/-', NULL, 'bashundhara', 6),
(227, 'SPA & BODY SCRUB', 'Uniliver Scrab (Full Body Scrab)', '6,000/-', NULL, 'bashundhara', 7),
(228, 'SPA & BODY SCRUB', 'Body Shop Back Scrab', '5,000/-', NULL, 'bashundhara', 8),
(229, 'SPA & BODY SCRUB', 'Body Shop Hand Scrab', '1,500/-', NULL, 'bashundhara', 9),
(230, 'SPA & BODY SCRUB', 'Body Shop Foot Scrab', '2,000/-', NULL, 'bashundhara', 10),
(231, 'SPA & BODY SCRUB', 'Alovera Body Scrab (Full Body)', '5,000/-', NULL, 'bashundhara', 11),
(232, 'SPA & BODY SCRUB', 'Royal Body Smoothing Scrab', '16,000/-', NULL, 'bashundhara', 12),
(233, 'HAND & FOOT CARE', 'Manicure', '700/-', NULL, 'bashundhara', 0),
(234, 'HAND & FOOT CARE', 'Pedicure', '1,000/-', NULL, 'bashundhara', 1),
(235, 'HAND & FOOT CARE', 'Manicure Deluxe', '1,000/-', NULL, 'bashundhara', 2),
(236, 'HAND & FOOT CARE', 'Pedicure Deluxe', '2,000/-', NULL, 'bashundhara', 3),
(237, 'FACIAL', 'Adonis Special', '3,500/-', NULL, 'bashundhara', 0),
(238, 'FACIAL', 'Aloe Vera facial for all types of skin', '3,000/-', NULL, 'bashundhara', 1),
(239, 'FACIAL', 'Pearl Facial', '4,000/-', NULL, 'bashundhara', 2),
(240, 'FACIAL', 'Gold Facial', '5,000/-', NULL, 'bashundhara', 3),
(241, 'FACIAL', 'Diamond Facial', '4,500/-', NULL, 'bashundhara', 4),
(242, 'FACIAL', 'Janssen Man Facial', '7,000/-', NULL, 'bashundhara', 5),
(243, 'FACIAL', 'Janssen Whitening facial for all types of skin', '7,000/-', NULL, 'bashundhara', 6),
(244, 'FACIAL', 'Lotus Gold', '8,000/-', NULL, 'bashundhara', 7),
(245, 'FACIAL', 'Lotus Platinum', '10,000/-', NULL, 'bashundhara', 8),
(246, 'FACIAL', 'Body Shop Vitamin-C Facial', '7,000/-', NULL, 'bashundhara', 9),
(247, 'FACIAL', 'Body Shop Seedwed', '9,000/-', NULL, 'bashundhara', 10),
(248, 'FACIAL', 'Body Shop Drops of Light', '12,000/-', NULL, 'bashundhara', 11),
(249, 'FACIAL', 'Janssen Whitening Facial (Orange)', '8,000/-', NULL, 'bashundhara', 12),
(250, 'MASSAGE LAB', 'Neck, Head & Foot Massage (60 Minutes)', '2,200/-', NULL, 'bashundhara', 0),
(251, 'MASSAGE LAB', 'Neck, Head & Foot Massage (90 Minutes)', '3,000/-', NULL, 'bashundhara', 1),
(252, 'MASSAGE LAB', 'Back, Neck & Shoulder Massage (30 Minutes)', '1,500/-', NULL, 'bashundhara', 2),
(253, 'MASSAGE LAB', 'Thai Foot Reflexology (45 Minutes)', '1,200/-', NULL, 'bashundhara', 3),
(254, 'MASSAGE LAB', 'Thai Foot Reflexology (60 Minutes)', '1,500/-', NULL, 'bashundhara', 4),
(255, 'MASSAGE LAB', 'Thai Foot Reflexology (90 Minutes)', '2,000/-', NULL, 'bashundhara', 5),
(256, 'MASSAGE LAB', 'Head Massage with Hair Tonic (15 Minutes)', '1,000/-', NULL, 'bashundhara', 6),
(257, 'MASSAGE LAB', 'Head Massage without Hair Tonic (15 Minutes)', '600/-', NULL, 'bashundhara', 7),
(258, 'MASSAGE LAB', 'Chair Massage (20 Minutes)', '1,000/-', NULL, 'bashundhara', 8),
(259, 'MASSAGE LAB', 'Indian / Traditional Massage (60 Minutes)', '2,500/-', NULL, 'bashundhara', 9),
(260, 'MASSAGE LAB', 'Indian / Traditional Massage (90 Minutes)', '3,500/-', NULL, 'bashundhara', 10),
(261, 'MASSAGE LAB', 'Deep Tissue Body Massage (60 Minutes)', '3,000/-', NULL, 'bashundhara', 11),
(262, 'MASSAGE LAB', 'Deep Tissue Body Massage (90 Minutes)', '4,000/-', NULL, 'bashundhara', 12),
(263, 'MASSAGE LAB', 'Thai Body Massage (60 Minutes)', '3,000/-', NULL, 'bashundhara', 13),
(264, 'MASSAGE LAB', 'Thai Body Massage (90 Minutes)', '4,000/-', NULL, 'bashundhara', 14),
(265, 'MASSAGE LAB', 'Bamboo Massage (30 Minutes)', '3,200/-', NULL, 'bashundhara', 15),
(266, 'MASSAGE LAB', 'Bamboo Massage (90 Minutes)', '4,500/-', NULL, 'bashundhara', 16),
(267, 'MASSAGE LAB', 'Hot Stone Massage (30 Minutes)', '3,500/-', NULL, 'bashundhara', 17),
(268, 'MASSAGE LAB', 'Hot Stone Massage (90 Minutes)', '4,600/-', NULL, 'bashundhara', 18),
(269, 'MASSAGE LAB', 'Swedish Massage (60 Minutes)', '3,000/-', NULL, 'bashundhara', 19),
(270, 'MASSAGE LAB', 'Swedish Massage (90 Minutes)', '4,000/-', NULL, 'bashundhara', 20),
(271, 'MASSAGE LAB', 'Aroma Massage (60 Minutes)', '2,600/-', NULL, 'bashundhara', 21),
(272, 'MASSAGE LAB', 'Aroma Massage (90 Minutes)', '3,500/-', NULL, 'bashundhara', 22)
ON DUPLICATE KEY UPDATE
  category = VALUES(category),
  name = VALUES(name),
  price = VALUES(price),
  description = VALUES(description),
  branch_id = VALUES(branch_id),
  sort_order = VALUES(sort_order);

